default_language_version:
    python: python3.9
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character.
    -   id: name-tests-test
        args: ['--django']
        exclude: tests/base.py
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
        args:
        - --markdown-linebreak-ext=md
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.0
    hooks:
    -   id: autopep8
        # There is a list slicing conflict with black. autopep8 = [:], black = [ :]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
    -   id: pyupgrade
        args:
        - --py38-plus
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        args:
        - -iii
        - -ll
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies:
        - flake8-bugbear
        - flake8-comprehensions
        - flake8-mutable
        - flake8-print
        - flake8-simplify
-   repo: https://github.com/pycqa/pylint
    rev: v2.15.5
    hooks:
    -   id: pylint
        exclude: '[a-zA-Z]*/(migrations)/(.)*'
